### ISSUE TITLE
unspected limits behaviour

### ISSUE THREAD

**Issue by psigelo** [astng/ai_data_analysis#3]
the limits change in time.

example to reproduce: using mongo

`db.raw_data.find({"component_type": 681, "component": 3751}, {"ironLSC":1, "_id":0})`

retult in:

`{ "ironLSC" : 35 }
{ "ironLSC" : 100 }
{ "ironLSC" : 200 }
{ "ironLSC" : 200 }
{ "ironLSC" : 200 }
{ "ironLSC" : 200 }
{ "ironLSC" : 30 }
{ "ironLSC" : 35 }
{ "ironLSC" : 100 }
{ "ironLSC" : 200 }
{ "ironLSC" : 200 }
{ "ironLSC" : 200 }
{ "ironLSC" : 200 }
{ "ironLSC" : 30 }
{ "ironLSC" : 35 }
{ "ironLSC" : 100 }
{ "ironLSC" : 200 }
{ "ironLSC" : 200 }
{ "ironLSC" : 200 }
{ "ironLSC" : 200 }`

it seems that the protocol id is changing over the component lifetime, this is possibly?

**Comment by miguel-a-solis** [comment]
id_protocol actually changes over samples for a particular (machine_type, component_type, component), at least from database. Behavior to be confirmed with client

**Comment by miguel-a-solis** [comment]
client says that limits should be constant, unexpected behavior may be due to mixture of clients within the same id_component (every client may set different limits). TAG should be taken as unique identifier for such purposes

**Comment by miguel-a-solis** [comment]
still unexpected behavior for a given TAG, id_protocol applied seems to vary for certain tags, for instance see:
- constant LSC and id_protocol: https://github.com/astng/ai_data_analysis/blob/master/figures/iron-plots/iron-tagZA1-1123-TRH001-HYD-HOSY.pdf
- constant LSC and changing id_protocol: https://github.com/astng/ai_data_analysis/blob/master/figures/iron-plots/iron-tag700LUM1009M100.pdf
- changing LSC and id_protocol: https://github.com/astng/ai_data_analysis/blob/master/figures/iron-plots/iron-tag123R04112MI.pdf

**Comment by miguel-a-solis** [comment]
finally component individualization could be obtained through TAG or id_component as unique identifier for a given component (whose behavior may vary for other similar component from other component_type, machine_type or client, but this would correspond to a different id_component). 

Changing limits behavior as indicated earlier from client, may vary for the same id_component through different samples due to final-client requirements about changing applied protocol.
